config/routes.rb
Opentheatre::Application.routes.draw do

  namespace :admin do
    get '/', :to => 'dashboard#show'
    resources :movies do
      collection do
        post :search
      end
    end
  end

  resources :movies

end

app/models/movie.rb
class Movie < ActiveRecord::Base
  extend FriendlyId
  friendly_id :title, use: [:slugged, :finders]

  mount_uploader :poster, PosterUploader
end

app/controllers/admin/dashboard_controller.rb
class Admin::DashboardController < ApplicationController
  def show
  end
end

app/controllers/admin/movies_controller.rb
class Admin::MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def search
    @movies = Tmdb::Movie.find(params[:q])
  end

  def show
    @movie = Movie.find(params[:id])
  end

  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.create(movie_params)
    redirect_to admin_movies_path, notice: "The movie has been created."
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    @movie.update_attributes(movie_params)
    redirect_to admin_movies_path, notice: "The movie has been updated."
  end

private

  def movie_params
    params.require(:movie).permit(:title, :overview, :poster)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  add_flash_types :notice, :error
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  def index
    @movies = Movie.all
  end

  def show
    @movie = Movie.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def poster_path(movie)
    configuration = Tmdb::Configuration.new
    configuration.base_url + "w92" + movie.poster_path
  end

end

app/views/admin/dashboard/show.html.haml
.page-header
  %h1 Dashboard

%p Welcome to the admin dashboard

app/views/admin/movies/edit.html.haml
- model_class = Movie
.page-header
  %h1= t '.title', :default => [:'helpers.titles.new', 'Edit %{model}'], :model => model_class.model_name.human.titleize

= simple_form_for [:admin, @movie], :html => { :class => 'form-horizontal' } do |f|
  = f.input :title
  = f.input :overview
  = f.input :slug
  = f.input :poster, :as => :image_preview
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), movies_path, :class => 'btn'

app/views/admin/movies/index.html.haml
- model_class = Movie
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:overview)
      %th= model_class.human_attribute_name(:slug)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @movies.each do |movie|
      %tr
        %td= link_to movie.id, movie_path(movie)
        %td= movie.title
        %td= movie.overview
        %td= movie.slug
        %td=l movie.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_movie_path(movie), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_movie_path(movie), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

= link_to t('.new', :default => t("helpers.links.new")), new_admin_movie_path, :class => 'btn btn-primary'

app/views/admin/movies/new.html.haml
- model_class = Movie
.page-header
  %h1= t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize

= form_tag search_admin_movies_path, :method => :post, :class => 'search form-search' do
  .input-append
    = text_field_tag :q, params[:q], :class => 'search-query'
    = submit_tag 'Search', :class => 'btn'

= simple_form_for [:admin, @movie], :html => { :class => 'form-horizontal' } do |f|
  = f.input :title
  = f.input :overview
  = f.input :slug
  = f.input :poster, :as => :image_preview
  .form-actions
    = f.button :submit, :class => 'btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), movies_path, :class => 'btn'

app/views/admin/movies/search.html.haml
%table.search_results
  %tr
    %th
    %th Poster
    %th Title
  - @movies.each do |movie|
    %tr
      %td
      %td= image_tag poster_path(movie)
      %td= movie.title

app/views/admin/movies/show.html.haml
- model_class = Movie
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize

%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @movie.title
%p
  %strong= model_class.human_attribute_name(:overview) + ':'
  %br
  = @movie.overview
%p
  %strong= model_class.human_attribute_name(:slug) + ':'
  %br
  = @movie.slug

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), admin_movies_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_admin_movie_path(@movie), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), admin_movie_path(@movie), :method => "delete", :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Opentheatre"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"


  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          %a.btn.btn-navbar(data-target=".nav-collapse" data-toggle="collapse")
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand(href="#") Opentheatre
          .container.nav-collapse
            %ul.nav
              %li= link_to "Admin panel", "/admin"
              %li= link_to "Movies", "/movies"

    .container
      .row
        .span9
          = bootstrap_flash
          = yield
        .span3
          .well.sidebar-nav
            %h3 Sidebar
            %ul.nav.nav-list
              %li.nav-header Sidebar
              %li= link_to "Movies", "/admin/movies"
    
      %footer
        %p &copy; OpenTheater 2013

app/views/movies/index.html.haml
- model_class = Movie
.page-header
  %h1=t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:title)
      %th= model_class.human_attribute_name(:overview)
      %th= model_class.human_attribute_name(:slug)
      %th= model_class.human_attribute_name(:created_at)
      %th=t '.actions', :default => t("helpers.actions")
  %tbody
    - @movies.each do |movie|
      %tr
        %td= link_to movie.id, movie_path(movie)
        %td= movie.title
        %td= movie.overview
        %td= movie.slug
        %td=l movie.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_movie_path(movie), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), movie_path(movie), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'

app/views/movies/show.html.haml
- model_class = Movie
.page-header
  %h1=t '.title', :default => model_class.model_name.human.titleize
%p
  .poster= image_tag @movie.poster.url
%p
  %strong= model_class.human_attribute_name(:title) + ':'
  %br
  = @movie.title
%p
  %strong= model_class.human_attribute_name(:overview) + ':'
  %br
  = @movie.overview
%p
  %strong= model_class.human_attribute_name(:slug) + ':'
  %br
  = @movie.slug